version: '3'
services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - backend-db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend-db:
    image: mongo
    ports:
      - "27017:27017"
